/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminConvitesRouteImport } from './routes/admin-convites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SlugPedidoRouteImport } from './routes/$slug.pedido'
import { Route as AuthenticatedAdminPrecosRouteImport } from './routes/_authenticated/admin-precos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedConfiguracoesConvitesRouteImport } from './routes/_authenticated/configuracoes/convites'
import { Route as AuthenticatedConfiguracoesEnderecoRouteImport } from './routes/_authenticated/configuracoes/endereco'
import { Route as AuthenticatedConfiguracoesIdentificacaoRouteImport } from './routes/_authenticated/configuracoes/identificacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConvitesRoute = AdminConvitesRouteImport.update({
  id: '/admin-convites',
  path: '/admin-convites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPedidoRoute = SlugPedidoRouteImport.update({
  id: '/$slug/pedido',
  path: '/$slug/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPrecosRoute =
  AuthenticatedAdminPrecosRouteImport.update({
    id: '/admin-precos',
    path: '/admin-precos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesConvitesRoute =
  AuthenticatedConfiguracoesConvitesRouteImport.update({
    id: '/configuracoes/convites',
    path: '/configuracoes/convites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesEnderecoRoute =
  AuthenticatedConfiguracoesEnderecoRouteImport.update({
    id: '/configuracoes/endereco',
    path: '/configuracoes/endereco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIdentificacaoRoute =
  AuthenticatedConfiguracoesIdentificacaoRouteImport.update({
    id: '/configuracoes/identificacao',
    path: '/configuracoes/identificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-convites': typeof AdminConvitesRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/$slug/pedido': typeof SlugPedidoRoute
  '/admin-precos': typeof AuthenticatedAdminPrecosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/configuracoes/convites': typeof AuthenticatedConfiguracoesConvitesRoute
  '/configuracoes/endereco': typeof AuthenticatedConfiguracoesEnderecoRoute
  '/configuracoes/identificacao': typeof AuthenticatedConfiguracoesIdentificacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-convites': typeof AdminConvitesRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/$slug/pedido': typeof SlugPedidoRoute
  '/admin-precos': typeof AuthenticatedAdminPrecosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/configuracoes/convites': typeof AuthenticatedConfiguracoesConvitesRoute
  '/configuracoes/endereco': typeof AuthenticatedConfiguracoesEnderecoRoute
  '/configuracoes/identificacao': typeof AuthenticatedConfiguracoesIdentificacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-convites': typeof AdminConvitesRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/$slug/pedido': typeof SlugPedidoRoute
  '/_authenticated/admin-precos': typeof AuthenticatedAdminPrecosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/configuracoes/convites': typeof AuthenticatedConfiguracoesConvitesRoute
  '/_authenticated/configuracoes/endereco': typeof AuthenticatedConfiguracoesEnderecoRoute
  '/_authenticated/configuracoes/identificacao': typeof AuthenticatedConfiguracoesIdentificacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-convites'
    | '/auth'
    | '/redefinir-senha'
    | '/$slug/pedido'
    | '/admin-precos'
    | '/clientes'
    | '/dashboard'
    | '/painel'
    | '/configuracoes/convites'
    | '/configuracoes/endereco'
    | '/configuracoes/identificacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-convites'
    | '/auth'
    | '/redefinir-senha'
    | '/$slug/pedido'
    | '/admin-precos'
    | '/clientes'
    | '/dashboard'
    | '/painel'
    | '/configuracoes/convites'
    | '/configuracoes/endereco'
    | '/configuracoes/identificacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-convites'
    | '/auth'
    | '/redefinir-senha'
    | '/$slug/pedido'
    | '/_authenticated/admin-precos'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/painel'
    | '/_authenticated/configuracoes/convites'
    | '/_authenticated/configuracoes/endereco'
    | '/_authenticated/configuracoes/identificacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminConvitesRoute: typeof AdminConvitesRoute
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SlugPedidoRoute: typeof SlugPedidoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-convites': {
      id: '/admin-convites'
      path: '/admin-convites'
      fullPath: '/admin-convites'
      preLoaderRoute: typeof AdminConvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/pedido': {
      id: '/$slug/pedido'
      path: '/$slug/pedido'
      fullPath: '/$slug/pedido'
      preLoaderRoute: typeof SlugPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-precos': {
      id: '/_authenticated/admin-precos'
      path: '/admin-precos'
      fullPath: '/admin-precos'
      preLoaderRoute: typeof AuthenticatedAdminPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/convites': {
      id: '/_authenticated/configuracoes/convites'
      path: '/configuracoes/convites'
      fullPath: '/configuracoes/convites'
      preLoaderRoute: typeof AuthenticatedConfiguracoesConvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/endereco': {
      id: '/_authenticated/configuracoes/endereco'
      path: '/configuracoes/endereco'
      fullPath: '/configuracoes/endereco'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEnderecoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/identificacao': {
      id: '/_authenticated/configuracoes/identificacao'
      path: '/configuracoes/identificacao'
      fullPath: '/configuracoes/identificacao'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIdentificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminPrecosRoute: typeof AuthenticatedAdminPrecosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedConfiguracoesConvitesRoute: typeof AuthenticatedConfiguracoesConvitesRoute
  AuthenticatedConfiguracoesEnderecoRoute: typeof AuthenticatedConfiguracoesEnderecoRoute
  AuthenticatedConfiguracoesIdentificacaoRoute: typeof AuthenticatedConfiguracoesIdentificacaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminPrecosRoute: AuthenticatedAdminPrecosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedConfiguracoesConvitesRoute:
    AuthenticatedConfiguracoesConvitesRoute,
  AuthenticatedConfiguracoesEnderecoRoute:
    AuthenticatedConfiguracoesEnderecoRoute,
  AuthenticatedConfiguracoesIdentificacaoRoute:
    AuthenticatedConfiguracoesIdentificacaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminConvitesRoute: AdminConvitesRoute,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SlugPedidoRoute: SlugPedidoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
